version: '2'
services:
  tutorial_jhipster_bugtracker-app:
    image: tutorial_jhipster_bugtracker
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://tutorial_jhipster_bugtracker-mysql:3306/tutorial_jhipster_bugtracker?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  tutorial_jhipster_bugtracker-mysql:
    extends:
      file: mysql.yml
      service: tutorial_jhipster_bugtracker-mysql
